version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Main frontend
      - "3001:3001"  # DoneEZ frontend
      - "8000:8000"  # Django backend
    env_file:
      - .env
      - DoneEZ/DoneEZ/.env
    environment:
      - NODE_ENV=production
      - DJANGO_SETTINGS_MODULE=doneez.settings
    volumes:
      - static_volume:/app/backend/static
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/var/www/static:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  static_volume: