# Generated by Django 4.2.16 on 2024-10-10 14:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_mechanicprofile_address_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
