# Generated by Django 4.2.16 on 2024-10-29 12:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mechanicprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='offered_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
    ]
