# Generated by Django 5.2.6 on 2025-09-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mechanicprofile_offered_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='location',
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='offered_services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
